# Generated by Django 4.2.6 on 2023-10-21 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='appaprendizajeForm',
            fields=[
                ('id_recursodigital', models.AutoField(primary_key=True, serialize=False)),
                ('Microsoft_OneDrive_Google_Drive', models.BooleanField(default=False)),
                ('Microsoft_o_Google_Calendar', models.BooleanField(default=False)),
                ('Sharepoint', models.BooleanField(default=False)),
                ('Microsoft_Sway', models.BooleanField(default=False)),
                ('Microsoft_Forms', models.BooleanField(default=False)),
                ('Microsoft_PowerBI', models.BooleanField(default=False)),
                ('Microsoft_Excel', models.BooleanField(default=False)),
                ('Microsoft_Planner', models.BooleanField(default=False)),
                ('Microsoft_Power_Automate', models.BooleanField(default=False)),
                ('Microsoft_Project', models.BooleanField(default=False)),
                ('Microsoft_Teams', models.BooleanField(default=False)),
                ('Microsoft_Yammer', models.BooleanField(default=False)),
                ('Kahoot', models.BooleanField(default=False)),
                ('Google_Formularios', models.BooleanField(default=False)),
                ('Google_Jamboard', models.BooleanField(default=False)),
                ('Slack', models.BooleanField(default=False)),
                ('Google_Padlet', models.BooleanField(default=False)),
                ('Google_Meet', models.BooleanField(default=False)),
                ('Google_Classroom', models.BooleanField(default=False)),
                ('Google_Drawing', models.BooleanField(default=False)),
                ('Google_Sites', models.BooleanField(default=False)),
                ('Google_Blogger', models.BooleanField(default=False)),
                ('Google_Earth', models.BooleanField(default=False)),
                ('Google_Collections', models.BooleanField(default=False)),
                ('Google_Currents', models.BooleanField(default=False)),
                ('Google_Docs', models.BooleanField(default=False)),
                ('Google_Sheets', models.BooleanField(default=False)),
                ('Google_Slides', models.BooleanField(default=False)),
                ('Google_Expeditions', models.BooleanField(default=False)),
                ('Asana', models.BooleanField(default=False)),
                ('Trello', models.BooleanField(default=False)),
                ('VPN', models.BooleanField(default=False)),
                ('Camscanner', models.BooleanField(default=False)),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Formulario_APP_Aprendizaje',
            },
        ),
    ]
