# Generated by Django 3.2.21 on 2023-09-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentform',
            name='genero',
            field=models.CharField(default=1, max_length=50, verbose_name='Enter last name'),
            preserve_default=False,
        ),
    ]
