# Generated by Django 4.2.6 on 2023-10-13 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioform',
            name='Fecha_Nacimiento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='HijoForm',
            fields=[
                ('id_Hijo', models.AutoField(primary_key=True, serialize=False)),
                ('Nombres_Hijo', models.CharField(max_length=20)),
                ('Apellido_Hijo', models.CharField(max_length=20)),
                ('Fecha_Nacimiento_Hijo', models.DateField(default=django.utils.timezone.now)),
                ('Cuidador_Hijo', models.CharField(choices=[('Pareja', 'Pareja'), ('Abuelos', 'Abuelos'), ('Otro Familiar', 'Otro Familiar'), ('Ciudador(a)', 'Ciudador(a)'), ('Guardería', 'Guardería'), ('No Requiere', 'No Requiere')], max_length=50)),
                ('Convivencia_Hijo', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2)),
                ('Requiere_Lugar_Para_Llevar_hijo', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2)),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Hijos',
            },
        ),
    ]
