# Generated by Django 4.2.6 on 2023-11-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiardiscapacidadform',
            old_name='abuela',
            new_name='abuelo_a',
        ),
        migrations.RenameField(
            model_name='familiardiscapacidadform',
            old_name='abuelo',
            new_name='cuñado_a',
        ),
        migrations.RenameField(
            model_name='familiardiscapacidadform',
            old_name='cuñada',
            new_name='esposo_a',
        ),
        migrations.RenameField(
            model_name='familiardiscapacidadform',
            old_name='cuñado',
            new_name='hermano_a',
        ),
        migrations.RenameField(
            model_name='familiardiscapacidadform',
            old_name='esposa',
            new_name='hijo_a',
        ),
        migrations.RenameField(
            model_name='familiardiscapacidadform',
            old_name='esposo',
            new_name='nieto_a',
        ),
        migrations.RenameField(
            model_name='familiardiscapacidadform',
            old_name='hermana',
            new_name='primo_a',
        ),
        migrations.RenameField(
            model_name='familiardiscapacidadform',
            old_name='hermano',
            new_name='sobrino_a',
        ),
        migrations.RenameField(
            model_name='familiardiscapacidadform',
            old_name='hija',
            new_name='suegro_a',
        ),
        migrations.RenameField(
            model_name='familiardiscapacidadform',
            old_name='hijo',
            new_name='tio_a',
        ),
        migrations.RemoveField(
            model_name='familiardiscapacidadform',
            name='nieta',
        ),
        migrations.RemoveField(
            model_name='familiardiscapacidadform',
            name='nieto',
        ),
        migrations.RemoveField(
            model_name='familiardiscapacidadform',
            name='prima',
        ),
        migrations.RemoveField(
            model_name='familiardiscapacidadform',
            name='primo',
        ),
        migrations.RemoveField(
            model_name='familiardiscapacidadform',
            name='sobrina',
        ),
        migrations.RemoveField(
            model_name='familiardiscapacidadform',
            name='sobrino',
        ),
        migrations.RemoveField(
            model_name='familiardiscapacidadform',
            name='suegra',
        ),
        migrations.RemoveField(
            model_name='familiardiscapacidadform',
            name='suegro',
        ),
        migrations.RemoveField(
            model_name='familiardiscapacidadform',
            name='tia',
        ),
        migrations.RemoveField(
            model_name='familiardiscapacidadform',
            name='tio',
        ),
        migrations.AlterField(
            model_name='familiarform',
            name='Fecha_Nacimiento_Familiar',
            field=models.DateField(),
        ),
    ]
