# Generated by Django 4.2.6 on 2023-11-10 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0002_experienciaslaboralesform_descripcion_experiencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienciaslaboralesform',
            name='idUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='evaluaciondesempenoForm',
            fields=[
                ('id_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('examenes', models.FloatField(default=0)),
                ('experiencia', models.FloatField(default=0)),
                ('educacion', models.FloatField(default=0)),
                ('competencias', models.FloatField(default=0)),
                ('suma_total', models.FloatField(default=0)),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Formulario_Evaluacion_Desempeno',
            },
        ),
    ]
