# Generated by Django 4.2.6 on 2023-10-23 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0002_appaprendizajeform'),
    ]

    operations = [
        migrations.CreateModel(
            name='ofrecimientoForm',
            fields=[
                ('id_ofrecimiento', models.AutoField(primary_key=True, serialize=False)),
                ('reconocimiento', models.BooleanField(default=False)),
                ('compensacion_economica', models.BooleanField(default=False)),
                ('actividades_de_voluntariado', models.BooleanField(default=False)),
                ('actividades_deportivas_recreacionales', models.BooleanField(default=False)),
                ('actividades_artisticas_culturales', models.BooleanField(default=False)),
                ('convenios_acceder_cursos_programas', models.BooleanField(default=False)),
                ('actividades_integracion_familiar', models.BooleanField(default=False)),
                ('patrocinios_educativos', models.BooleanField(default=False)),
                ('programas_situaciones_familiares', models.BooleanField(default=False)),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Formulario_Ofrecimientos',
            },
        ),
    ]
