# Generated by Django 4.2.6 on 2023-11-03 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_rename_abuela_familiardiscapacidadform_abuelo_a_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formularioform',
            name='Ultimo_Nivel_Educativo',
        ),
    ]
