# Generated by Django 4.2.6 on 2023-11-03 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0003_remove_formularioform_ultimo_nivel_educativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='historialeducativoFormn',
            fields=[
                ('id_estudio', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_titulo', models.CharField(choices=[(' Estiudiante', 'Estiudiante'), (' Primaria', 'Primaria'), (' Bachiller', 'Bachiller'), (' Tecnico', 'Tecnico'), (' Tecnólogo', 'Tecnólogo'), (' Licenciado', 'Licenciado'), (' Profesional: ', 'Profesional'), (' Especialista', 'Especialista'), (' Magister', 'Magister'), (' Maestria', 'Maestria'), (' Doctorado', 'Doctorado'), (' NR', 'NR')], max_length=30)),
                ('Descripcion_titulo', models.CharField(max_length=20)),
                ('Instituto_titulo', models.CharField(max_length=20)),
                ('Fecha_obtencion_titulo', models.DateField()),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
