# Generated by Django 4.2.6 on 2023-11-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_experienciaslaboralesform_iduser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contratacionform',
            old_name='Ingreso_Mensaul',
            new_name='Ingreso_Auxilio_monetario',
        ),
        migrations.AddField(
            model_name='contratacionform',
            name='Descripcion_Auxilio_Alimentos',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contratacionform',
            name='Descripcion_Auxilio_monetario',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contratacionform',
            name='Ingreso_Mensual_monetario',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contratacionform',
            name='Cargo_Contrato',
            field=models.CharField(choices=[('Academic Advisor', 'Academic Advisor'), ('Analista Contable', 'Analista Contable'), ('Analista de compensación', 'Analista de compensación'), ('Analista de comunicaciones', 'Analista de comunicaciones'), ('Analista de Gestión Organizacional', 'Analista de Gestión Organizacional'), ('Asesor Servicios Integrales', 'Asesor Servicios Integrales'), ('Asesora EduSA', 'Asesora EduSA'), ('Asistente Académico', 'Asistente Académico'), ('Asistente Cultural', 'Asistente Cultural'), ('Asistente de Comunicaciones', 'Asistente de Comunicaciones'), ('Asistente de Dirección', 'Asistente de Dirección'), ('Asistente de Innovación y Negocios', 'Asistente de Innovación y Negocios'), ('Asistente de Recursos Administrativos', 'Asistente de Recursos Administrativos'), ('Asistente de servicios bibliotecarios', 'Asistente de servicios bibliotecarios'), ('Asistente Maker', 'Asistente Maker'), ('Aprendiz', 'Aprendiz'), ('Auxiliar Contable', 'Auxiliar Contable'), ('Auxiliar de mantenimiento y recursos físicos', 'Auxiliar de mantenimiento y recursos físicos'), ('Auxiliar de Selección y contratación', 'Auxiliar de Selección y contratación'), ('Auxiliar de seguridad', 'Auxiliar de seguridad'), ('Auxiliar de Soporte Técnico', 'Auxiliar de Soporte Técnico'), ('Auxiliar Tecnología Educativa', 'Auxiliar Tecnología Educativa'), ('Coordinador académico sede sur', 'Coordinador académico sede sur'), ('Coordinador de acompañamiento psicosocial', 'Coordinador de acompañamiento psicosocial'), ('Coordinador de mercadeo', 'Coordinador de mercadeo'), ('Coordinador de proyectos especiales', 'Coordinador de proyectos especiales'), ('Coordinador de Programación y Gestión Comercial', 'Coordinador de Programación y Gestión Comercial'), ('Coordinador de servicios STEAM y bibliotecas', 'Coordinador de servicios STEAM y bibliotecas'), ('Coordinador sede virtual', 'Coordinador sede virtual'), ('Coordinadora de programa Kids and Teens', 'Coordinadora de programa Kids and Teens'), ('Coordinadora de responsabilidad social y egresados', 'Coordinadora de responsabilidad social y egresados'), ('Coordinadora sede norte', 'Coordinadora sede norte'), ('Desarrollador de producto', 'Desarrollador de producto'), ('Director Cultural', 'Director Cultural'), ('Director de Innovación y negocios', 'Director de Innovación y negocios'), ('Director Financiero y Administrativo', 'Director Financiero y Administrativo'), ('Director General', 'Director General'), ('Docente', 'Docente'), ('Jefe de Comunicaciones', 'Jefe de Comunicaciones'), ('Jefe de Contabilidad', 'Jefe de Contabilidad'), ('Jefe de Desarrollo de Producto', 'Jefe de Desarrollo de Producto'), ('Jefe de Gestión Humana', 'Jefe de Gestión Humana'), ('Jefe de Gestión Organizacional', 'Jefe de Gestión Organizacional'), ('Jefe de mantenimiento y recursos físicos', 'Jefe de mantenimiento y recursos físicos'), ('Jefe de Servicios Culturales', 'Jefe de Servicios Culturales'), ('Jefe de Servicios Integrales', 'Jefe de Servicios Integrales'), ('Recepcionista', 'Recepcionista'), ('Subdirector académico', 'Subdirector académico'), ('Support Teacher', 'Support Teacher'), ('Técnico electricista', 'Técnico electricista'), ('Técnico electrónico', 'Técnico electrónico'), ('Conductor-mensajero', 'Conductor-mensajero'), ('Academic Advisor', 'Academic Advisor'), ('Accountant Analyst', 'Accountant Analyst'), ('Compensation Analyst', 'Compensation Analyst'), ('Communications Analyst', 'Communications Analyst'), ('Organizational Management Analyst', 'Organizational Management Analyst'), ('Comprehensive Services Advisor', 'Comprehensive Services Advisor'), ('EduSA Advisor', 'EduSA Advisor'), ('Academic Assistant', 'Academic Assistant'), ('Cultural Assistant', 'Cultural Assistant'), ('Communications Assistant', 'Communications Assistant'), ('Executive Assistant', 'Executive Assistant'), ('Innovation and Business Assistant', 'Innovation and Business Assistant'), ('Administrative Resources Assistant', 'Administrative Resources Assistant'), ('Library Services Assistant', 'Library Services Assistant'), ('Maker Assistant', 'Maker Assistant'), ('Apprentice', 'Apprentice'), ('Accounting Assistant', 'Accounting Assistant'), ('Maintenance and Physical Resources Assistant', 'Maintenance and Physical Resources Assistant'), ('Selection and Hiring Assistant', 'Selection and Hiring Assistant'), ('Security Assistant', 'Security Assistant'), ('Technical Support Assistant', 'Technical Support Assistant'), ('Educational Technology Assistant', 'Educational Technology Assistant'), ('South Campus Academic Coordinator', 'South Campus Academic Coordinator'), ('Psychosocial Support Coordinator', 'Psychosocial Support Coordinator'), ('Marketing Coordinator', 'Marketing Coordinator'), ('Special Projects Coordinator', 'Special Projects Coordinator'), ('Programming and Commercial Management Coordinator', 'Programming and Commercial Management Coordinator'), ('STEAM and Libraries Services Coordinator', 'STEAM and Libraries Services Coordinator'), ('Virtual Campus Coordinator', 'Virtual Campus Coordinator'), ('Kids and Teens Program Coordinator', 'Kids and Teens Program Coordinator'), ('Social Responsibility and Alumni Coordinator', 'Social Responsibility and Alumni Coordinator'), ('North Campus Coordinator', 'North Campus Coordinator'), ('Product Developer', 'Product Developer'), ('Cultural Director', 'Cultural Director'), ('Innovation and Business Director', 'Innovation and Business Director'), ('Financial and Administrative Director', 'Financial and Administrative Director'), ('General Director', 'General Director'), ('Teacher', 'Teacher'), ('Communications Manager', 'Communications Manager'), ('Accounting Manager', 'Accounting Manager'), ('Product Development Manager', 'Product Development Manager'), ('Human Resources Manager', 'Human Resources Manager'), ('Organizational Management Manager', 'Organizational Management Manager'), ('Maintenance and Physical Resources Manager', 'Maintenance and Physical Resources Manager'), ('Cultural Services Manager', 'Cultural Services Manager'), ('Comprehensive Services Manager', 'Comprehensive Services Manager'), ('Receptionist', 'Receptionist'), ('Academic Subdirector', 'Academic Subdirector'), ('Support Teacher', 'Support Teacher'), ('Electrician Technician', 'Electrician Technician'), ('Electronic Technician', 'Electronic Technician')], max_length=100),
        ),
        migrations.AlterField(
            model_name='contratacionform',
            name='Tipo_Contrato',
            field=models.CharField(choices=[('Termino Fijo', 'Termino Fijo'), ('Indefinido', 'Indefinido'), ('Prestacion de Servicios', 'Prestacion de Servicios'), ('aprendizaje', 'aprendizaje'), ('Fixed Term', 'Fixed Term'), ('Indefinite', 'Indefinite'), ('Service Provision', 'Service Provision'), ('Apprenticeship', 'Apprenticeship')], max_length=28),
        ),
    ]
