# Generated by Django 4.2.6 on 2023-10-23 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0003_ofrecimientoform'),
    ]

    operations = [
        migrations.CreateModel(
            name='desarrollopersonalForm',
            fields=[
                ('id_desarrollopersonal', models.AutoField(primary_key=True, serialize=False)),
                ('Salud_financiera', models.BooleanField(default=False)),
                ('Relaciones_familiares', models.BooleanField(default=False)),
                ('Manejo_de_conflictos', models.BooleanField(default=False)),
                ('Manejo_de_adicciones', models.BooleanField(default=False)),
                ('Manejo_del_duelo', models.BooleanField(default=False)),
                ('Estilos_de_vida_saludable', models.BooleanField(default=False)),
                ('Salud_mental', models.BooleanField(default=False)),
                ('Cuidado_parental', models.BooleanField(default=False)),
                ('Enfermedades_crónicas', models.BooleanField(default=False)),
                ('Enfermedades_de_transmisión_sexual', models.BooleanField(default=False)),
                ('Prevención_y_manejo_del_cáncer', models.BooleanField(default=False)),
                ('Expresión_oral_y_corporal', models.BooleanField(default=False)),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Formulario_Desarrollo_Personal',
            },
        ),
    ]
