# Generated by Django 4.2.6 on 2023-11-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_historialeducativoformn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialeducativoformn',
            name='Descripcion_titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='historialeducativoformn',
            name='Instituto_titulo',
            field=models.CharField(max_length=200),
        ),
    ]
