# Generated by Django 4.2.6 on 2023-10-23 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0004_desarrollopersonalform'),
    ]

    operations = [
        migrations.CreateModel(
            name='reconocimientoempresarialForm',
            fields=[
                ('id_reconocimientoempresarial', models.AutoField(primary_key=True, serialize=False)),
                ('Participar_en_iniciativas_o_proyectos', models.BooleanField(default=False)),
                ('Viajes', models.BooleanField(default=False)),
                ('Bonos_en_dinero', models.BooleanField(default=False)),
                ('Flexibilidad_horaria', models.BooleanField(default=False)),
                ('Tiempo_libre', models.BooleanField(default=False)),
                ('Patrocinios_para_formación_profesional', models.BooleanField(default=False)),
                ('Patrocinios_para_desarrollo_personal', models.BooleanField(default=False)),
                ('Bonos_actividades_recreación', models.BooleanField(default=False)),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Formulario_Reconocimiento_Empresarial',
            },
        ),
    ]
