# Generated by Django 4.2.6 on 2023-11-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_rename_ingreso_mensaul_contratacionform_ingreso_auxilio_monetario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratacionform',
            name='Ingreso_Auxilio_Alimentos',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
