# Generated by Django 4.2.6 on 2023-11-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_contratacionform_ingreso_auxilio_alimentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratacionform',
            name='Descripcion_Carta_laboral',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
