# Generated by Django 4.2.6 on 2023-11-03 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_alter_historialeducativoformn_descripcion_titulo_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historialeducativoformn',
            table='Formulario_Historial_educativo',
        ),
    ]
