# Generated by Django 3.2.21 on 2023-09-28 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_alter_studentform_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentform',
            name='user',
        ),
    ]
