# Generated by Django 4.2.6 on 2023-11-03 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_alter_historialeducativoformn_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formularioform',
            name='Nivel_Educativo_Mas_Alto',
        ),
    ]
