# Generated by Django 4.2.6 on 2023-11-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_alter_contratacionform_ingreso_auxilio_alimentos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratacionform',
            name='Descripcion_Auxilio_Alimentos',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='contratacionform',
            name='Descripcion_Auxilio_monetario',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contratacionform',
            name='Descripcion_Carta_laboral',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='contratacionform',
            name='Fecha_Fin_Contrato',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contratacionform',
            name='Fecha_Inicio_Contrato',
            field=models.DateField(null=True),
        ),
    ]
