# Generated by Django 4.2.6 on 2023-11-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_remove_formularioform_nivel_educativo_mas_alto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratacionform',
            name='Es_flexibilizado',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
