# Generated by Django 4.2.6 on 2023-11-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_contratacionform_es_flexibilizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ooptform',
            fields=[
                ('id_oopt', models.AutoField(primary_key=True, serialize=False)),
                ('Resultado_oopt', models.CharField(choices=[(' A1', 'A1'), (' A2', 'A2'), (' B1', 'B1'), (' B2', 'B2'), (' C1', 'C1'), (' C2', 'C2'), (' No Aplica: ', 'No Aplica')], max_length=30)),
                ('Fecha_Presentacion_oopt', models.DateField()),
                ('Cumnplimiento_Proficiencia', models.FloatField()),
            ],
        ),
    ]
