# Generated by Django 4.2.6 on 2023-11-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_alter_contratacionform_descripcion_auxilio_alimentos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratacionform',
            name='Descripcion_Auxilio_Alimentos',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='contratacionform',
            name='Descripcion_Auxilio_monetario',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='contratacionform',
            name='Descripcion_Carta_laboral',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='contratacionform',
            name='Ingreso_Mensual_monetario',
            field=models.CharField(max_length=100),
        ),
    ]
