# Generated by Django 4.2.6 on 2023-11-09 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0009_ooptform'),
    ]

    operations = [
        migrations.AddField(
            model_name='ooptform',
            name='idUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='ooptform',
            table='Formulario_OOPT',
        ),
    ]
