# Generated by Django 3.2.21 on 2023-09-28 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_auto_20230928_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentform',
            old_name='user',
            new_name='User',
        ),
    ]
