# Generated by Django 4.2.6 on 2023-11-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_alter_contratacionform_descripcion_auxilio_alimentos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratacionform',
            name='Ingreso_Auxilio_Alimentos',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contratacionform',
            name='Ingreso_Auxilio_monetario',
            field=models.CharField(max_length=100),
        ),
    ]
