# Generated by Django 4.2.6 on 2023-11-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_alter_contratacionform_ingreso_auxilio_alimentos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiarform',
            name='Parentesco_Cuidador',
            field=models.CharField(choices=[('Pareja', 'Pareja'), ('Abuelos', 'Abuelos'), ('Otro Familiar', 'Otro Familiar'), ('Ciudador(a)', 'Ciudador(a)'), ('Guardería', 'Guardería'), ('No Requiere', 'No Requiere'), ('No Tengo Hijos', 'No Tengo Hijos')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='familiarform',
            name='Parentesco_Familiar',
            field=models.CharField(choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Hijo', 'Hijo'), ('Hija', 'Hija'), ('Hermano', 'Hermano'), ('Hermana', 'Hermana'), ('Abuelo', 'Abuelo'), ('Abuela', 'Abuela'), ('Nieto', 'Nieto'), ('Nieta', 'Nieta'), ('Tío', 'Tío'), ('Tía', 'Tía'), ('Sobrino', 'Sobrino'), ('Sobrina', 'Sobrina'), ('Primo', 'Primo'), ('Prima', 'Prima'), ('Cuñado', 'Cuñado'), ('Cuñada', 'Cuñada'), ('Suegro', 'Suegro'), ('Suegra', 'Suegra'), ('Yerno', 'Yerno'), ('Nuera', 'Nuera'), ('Padrino', 'Padrino'), ('Madrina', 'Madrina'), ('Ahijado', 'Ahijado'), ('Ahijada', 'Ahijada'), ('Esposo', 'Esposo'), ('Esposa', 'Esposa'), ('Compañero', 'Compañero'), ('Compañera', 'Compañera')], max_length=50),
        ),
    ]
