# Generated by Django 4.2.6 on 2023-11-09 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_ooptform_iduser_alter_ooptform_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ooptform',
            name='Cumnplimiento_Proficiencia',
        ),
    ]
