# Generated by Django 3.2.21 on 2023-09-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0011_alter_studentform_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentform',
            old_name='User',
            new_name='idUser',
        ),
        migrations.AlterField(
            model_name='studentform',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='studentform',
            name='firstname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentform',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentform',
            name='lastname',
            field=models.CharField(max_length=50),
        ),
    ]
