# Generated by Django 3.2.21 on 2023-09-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_auto_20230928_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentform',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
