# Generated by Django 4.2.6 on 2023-11-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0013_alter_formularioform_cargo_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioform',
            name='tipo_sangre',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('xs-', 'xs')], max_length=3),
        ),
    ]
