# Generated by Django 3.2.21 on 2023-09-28 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0013_alter_studentform_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentform',
            old_name='id',
            new_name='idstudent',
        ),
    ]
