# Generated by Django 3.2.21 on 2023-09-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0015_rename_idstudent_studentform_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentform',
            name='estado_civil',
            field=models.CharField(choices=[('1', 'Soltero(a)'), ('2', 'Casado(a)'), ('3', 'Unión Libre'), ('4', 'Viudo(a)')], default='1', max_length=1),
        ),
    ]
