# Generated by Django 3.2.21 on 2023-09-28 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0017_remove_studentform_estado_civil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentform',
            old_name='firstname',
            new_name='NumeroDocumento',
        ),
    ]
