# Generated by Django 3.2.21 on 2023-09-28 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0018_rename_firstname_studentform_numerodocumento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentform',
            old_name='NumeroDocumento',
            new_name='firstname',
        ),
    ]
