# Generated by Django 3.2.21 on 2023-09-28 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0020_rename_firstname_studentform_documento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentform',
            old_name='Documento',
            new_name='firstname',
        ),
    ]
