# Generated by Django 3.2.21 on 2023-09-29 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0021_rename_documento_studentform_firstname'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Documento', models.CharField(max_length=50)),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Formulario',
            },
        ),
        migrations.DeleteModel(
            name='StudentForm',
        ),
    ]
